# Generated by Django 2.2.5 on 2019-09-07 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='modified_date',
        ),
    ]
